// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace iSpan_final_service.Models
{
    public partial class Area
    {
        public Area()
        {
            Gym = new HashSet<Gym>();
        }

        public int AreaId { get; set; }
        public int? CountyId { get; set; }
        public string Village { get; set; }

        public virtual County County { get; set; }
        public virtual ICollection<Gym> Gym { get; set; }
    }
}