// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace iSpan_final_service.Models
{
    public partial class Award
    {
        public int AwardId { get; set; }
        public int MemberId { get; set; }
        public string AwardName { get; set; }
        public DateTime Date { get; set; }
    }
}