// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace iSpan_final_service.Models
{
    public partial class BackgroundManagement
    {
        public int UserId { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public int? Authority { get; set; }
    }
}