// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace iSpan_final_service.Models
{
    public partial class Board
    {
        public Board()
        {
            Article = new HashSet<Article>();
        }

        public int BoardId { get; set; }
        public string BoardName { get; set; }

        public virtual ICollection<Article> Article { get; set; }
    }
}