// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace iSpan_final_service.Models
{
    public partial class Calendar
    {
        public Calendar()
        {
            Match = new HashSet<Match>();
        }

        public int CalendarId { get; set; }
        public int ObjectId { get; set; }
        public int? OrdererId { get; set; }
        public DateTime StartDateTime { get; set; }
        public string MyContent { get; set; }
        public bool IsConfirmed { get; set; }
        public DateTime OrderDate { get; set; }

        public virtual ICollection<Match> Match { get; set; }
    }
}