// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace iSpan_final_service.Models
{
    public partial class ChatRoom
    {
        public int ChatId { get; set; }
        public int MemberStudentId { get; set; }
        public int MemberCoachId { get; set; }
        public string Context { get; set; }
        public DateTime Time { get; set; }
    }
}