// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace iSpan_final_service.Models
{
    public partial class Class
    {
        public int ClassId { get; set; }
        public string ClassName { get; set; }
    }
}