// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace iSpan_final_service.Models
{
    public partial class County
    {
        public County()
        {
            Area = new HashSet<Area>();
        }

        public int CountyId { get; set; }
        public string CountyName { get; set; }

        public virtual ICollection<Area> Area { get; set; }
    }
}