// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace iSpan_final_service.Models
{
    public partial class Equipment
    {
        public Equipment()
        {
            GymOrderEquipment = new HashSet<GymOrderEquipment>();
        }

        public int EquipmentId { get; set; }
        public string EquipmentName { get; set; }
        public int GymId { get; set; }

        public virtual ICollection<GymOrderEquipment> GymOrderEquipment { get; set; }
    }
}