// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace iSpan_final_service.Models
{
    public partial class FavoriteBoard
    {
        public int BoardId { get; set; }
        public int MemberId { get; set; }
    }
}