// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace iSpan_final_service.Models
{
    public partial class Gym
    {
        public Gym()
        {
            GymOrder = new HashSet<GymOrder>();
        }

        public int GymId { get; set; }
        public int AreaId { get; set; }
        public string GymName { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string ImgPath { get; set; }
        public string Web { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public bool? Validity { get; set; }

        public virtual Area Area { get; set; }
        public virtual ICollection<GymOrder> GymOrder { get; set; }
    }
}