// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace iSpan_final_service.Models
{
    public partial class GymOrder
    {
        public GymOrder()
        {
            GymOrderEquipment = new HashSet<GymOrderEquipment>();
        }

        public int GymOrderId { get; set; }
        public int GymId { get; set; }
        public int OrderId { get; set; }

        public virtual Gym Gym { get; set; }
        public virtual Match Order { get; set; }
        public virtual ICollection<GymOrderEquipment> GymOrderEquipment { get; set; }
    }
}