// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace iSpan_final_service.Models
{
    public partial class Inbody
    {
        public int InbodyId { get; set; }
        public int MemberId { get; set; }
        public DateTime Date { get; set; }
        public decimal Height { get; set; }
        public decimal Weight { get; set; }
        public decimal Smm { get; set; }
        public decimal Bfm { get; set; }
        public decimal Tbw { get; set; }
        public decimal Ffm { get; set; }
        public decimal Bmi { get; set; }
        public decimal Whr { get; set; }
        public decimal Bmr { get; set; }
    }
}