// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace iSpan_final_service.Models
{
    public partial class License
    {
        public int LicenseId { get; set; }
        public int MemberId { get; set; }
        public string LicenseName { get; set; }
        public DateTime Date { get; set; }
    }
}