// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace iSpan_final_service.Models
{
    public partial class Match
    {
        public Match()
        {
            GymOrder = new HashSet<GymOrder>();
        }

        public int MatchId { get; set; }
        public int? CalendarId { get; set; }
        public int Payment { get; set; }
        public bool IsPaid { get; set; }
        public DateTime OrderTime { get; set; }
        public DateTime? DealTime { get; set; }

        public virtual Calendar Calendar { get; set; }
        public virtual ICollection<GymOrder> GymOrder { get; set; }
    }
}