// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace iSpan_final_service.Models
{
    public partial class Member
    {
        public Member()
        {
            SurviceArea = new HashSet<SurviceArea>();
        }

        public int MemberId { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public string Mobile { get; set; }
        public bool? Gender { get; set; }
        public int? Age { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public int? Authority { get; set; }
        public int Credit { get; set; }
        public int Points { get; set; }
        public string Skill { get; set; }
        public int? Price { get; set; }
        public string Picture { get; set; }
        public string SelfIntro { get; set; }
        public bool? Validity { get; set; }

        public virtual ICollection<SurviceArea> SurviceArea { get; set; }
    }
}