// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace iSpan_final_service.Models
{
    public partial class Notice
    {
        public int MessageId { get; set; }
        public int MemberId { get; set; }
        public string NoticeLink { get; set; }
        public string NoticeTitle { get; set; }
        public bool IsClicked { get; set; }
    }
}