// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace iSpan_final_service.Models
{
    public partial class Reply
    {
        public int ReplyId { get; set; }
        public int ArticleId { get; set; }
        public int MemberId { get; set; }
        public string Context { get; set; }
        public DateTime Time { get; set; }
        public int NumNice { get; set; }
        public bool? Validity { get; set; }
        public bool IsRereply { get; set; }
        public string Picture { get; set; }
    }
}