// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace iSpan_final_service.Models
{
    public partial class Score
    {
        public int ObjectId { get; set; }
        public int MemberId { get; set; }
        public int Score1 { get; set; }
        public DateTime Date { get; set; }
        public bool Validity { get; set; }
    }
}